# Generated by Django 5.2.12 on 2026-03-17 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HAC', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartmentstaydetails',
            name='owner_property_photos',
        ),
        migrations.RemoveField(
            model_name='commericialdetails',
            name='owner_property_photos',
        ),
        migrations.RemoveField(
            model_name='stayhosteldetails',
            name='owner_property_photos',
        ),
    ]
